<script>
	import SwatchCards from './SwatchCards.svelte'
	import SwatchHeader from './SwatchHeader.svelte'
	import SwatchQualities from './SwatchQualities.svelte';
	import SwatchDescription from './SwatchDescription.svelte';
	import SwatchPigments from './SwatchPigments.svelte';
	import SwatchSimilarProducts from './SwatchSimilarProducts.svelte';
	import SwatchStats from './SwatchStats.svelte';
	import SwatchTags from './SwatchTags.svelte';
	import SwatchNotes from './SwatchNotes.svelte';

	export let swatchData;

	const swatch = {
		slug: 'some-autogenerated-unique-slug',
		published: true,
		tags: [
			{
				name: 'botanicals',
				slug: 'botanicals'
			},
			{
				name: 'high intensity',
				slug: 'high-intensity',
			}
		],
		paint: {
			paint_type: 'Watercolor',
			product_color_name: 'Burnt Bronzite Genuine',
			product_description: 'Burnt Bronzite Genuine is a more reddish version of Bronzite. When mixed with reds, you get warm skin tones. When mixed with French Ultramarine, there is a hint of violet. With Cerulean Blue Chromium, the gray looks neutral.',
			manufacturer_product_description: 'Gorgeous Burnt Bronzite Genuine pushes the honey tone of Bronzite Genuine to a more coppery hue. Both deeper brown and more orange, its ideal for portrait work as it easily produces a wide range of flesh tones. Like Bronzite Genuine, it gets a subtle lustrous sparkle from iron oxide.', 
			manufacturer_pigment_description: 'Genuine Bronzite | Series: 3' ,
			manufacturer_name: 'Daniel Smith',
			pigments: [
				{
					code: 'PY97',
					name: 'Arylide Yellow FGL',
					image_url: 'http://placekitten.com/50/50',
					slug: 'pigments/py97',
					color: {
						name: 'Yellow',
						code: 'Y'
					},
					number: 97,
				},
				{
					code: 'PB16',
					name: 'Phthalocyanine Turquoise',
					image_url: 'http://placekitten.com/50/50',
					slug: 'pigments/pb16',
					color: {
						name: 'Blue',
						code: 'B'
					},
					number: 16,
				},
			],
			similar_products: [
				{
					product_color_name: 'Burnt Bronzite Genuine',
					manufacturer_name: 'Daniel Smith',
					image_url: 'http://placekitten.com/50/50',
					slug: 'some-autogenerated-unique-slug',
				},
				{
					product_color_name: 'Burnt Bronzite Genuine',
					manufacturer_name: 'Daniel Smith',
					image_url: 'http://placekitten.com/50/50',
					slug: 'some-autogenerated-unique-slug',
				}
			],
			qualities: {
				lightfast_rating: {name: 'I - Excellent', description: '100+ years'},
				transparency_rating: {name: 'Semi-Transparent', description: ''},
				staining_rating: {name: '1', description: 'Non Staining'},
				granulation_rating: {name: 'Yes', description: ''},
			}
		},
		swatchCards: [
			{
				paper: {
					manufacturer: 'Arches', 
					description: 'Cold press', 
					weight_in_lbs: 130
				},
				swatch_type: 'gradient wash granulation',
				author: {display_name: 'jane doe'},
				custom_swatch_type: null,
				description: 'some notes about this particular image',
				image_url: 'http://placekitten.com/200/300'
			},
			{
				paper: {
					manufacturer: 'Arches', 
					description: 'Hot press', 
					weight_in_lbs: 120
				},
				swatch_type: 'salted',
				author: {display_name: 'jane doe'},
				custom_swatch_type: null,
				description: 'some notes about this particular image',
				image_url: 'http://placekitten.com/300/300'
			},
		],
		stats: [
			'<strong>19</strong> artists have this in their palette library',
			'<strong>28</strong> artists want this watercolor',
			'<strong>89%</strong> of artists who have used it are happy'
		],
		notes: [
			{
				date: '2 weeks ago',
				author: {
					display_name: 'Foo Jr.',
					initial: 'F',
				},
				body: '<p>Chrome titanate PBr24 is a very lightfast, opaque, staining, moderately light valued, moderately intense earth yellow pigment, available from about a dozen pigment manufacturers worldwide in shades ranging from green yellow through orange yellow (the shade currently used in watercolors) to dull red. The ASTM (1999) rates its lightfastness as "excellent" (I), and my own and manufacturer lightfastness tests agree. It was originally developed as a vinyl siding pigment that would weather gracefully under prolonged sunlight exposure.</p>',
				replies: [
					{
						date: '5 days ago',
						author: {
							display_name: 'Bar Baz',
							initial: 'B',
						},
						body: '<p>In watercolors PBr24 undergoes a very small drying shift, darkening by 5% and losing saturation slightly. The average CIECAM J,a,b values for chrome titanate (PBr24) are: 68, 24, 48, with chroma of 53 (estimated hue purity of 39) and a hue angle of 64. In watercolor paints described here the pigment is consistently a warm pale yellow; paints differ only in the milling and vehicle formulations.</p>'
					},
					{
						date: '5 days ago',
						author: {
							display_name: 'Fool4Paintz',
							initial: 'F',
						},
						body: '<p>In watercolors PBr24 undergoes a very small drying shift, darkening by 5% and losing saturation slightly!</p>'
					}
				]
			}
		]
	}
</script>
<h3>{swatchData?.productColorName}</h3>
<SwatchHeader title={swatch.paint.product_color_name} manufacturerName={swatch.paint.manufacturer_name} />
<SwatchCards swatchCards={swatch.swatchCards} />
<div class="row">
	<div class="column">
		<SwatchQualities qualities={swatch.paint.qualities} />
		<SwatchDescription
			productDescription={swatch.paint.product_description}
			manufacturerProductDescription={swatch.paint.manufacturer_product_description}
			manufacturerPigmentDescription={swatch.paint.manufacturer_pigment_description}
			manufacturerName={swatch.paint.manufacturer_name}
		/>
	</div>
	<div class="column">
		<SwatchPigments pigments={swatch.paint.pigments} />
		<SwatchSimilarProducts similarProducts={swatch.paint.similar_products} paintType={swatch.paint.paint_type} />
		<SwatchStats stats={swatch.stats} />
		<SwatchTags tags={swatch.tags} />
	</div>
</div>
<SwatchNotes notes={swatch.notes} />

<style>
	.row {
		display: flex;
	}
</style>