<script>
	import SwatchImage from './SwatchImage.svelte'
	import SwatchHeader from './SwatchHeader.svelte'

	const swatchCard = {
		slug: 'some-autogenerated-unique-slug',
		published: true,
		tags: [{id: 1}, {id: 2}, {id: 3}],
		swatches: [{id: 1}, {id: 2}, {id: 3}]
	}
	
	const paint = {
		product_color_name: 'Burnt Bronzite Genuine',
		product_description: 'something',
		manufacturer_product_description: 'Gorgeous Burnt Bronzite Genuine pushes the honey tone of Bronzite Genuine to a more coppery hue. Both deeper brown and more orange, its ideal for portrait work as it easily produces a wide range of flesh tones. Like Bronzite Genuine, it gets a subtle lustrous sparkle from iron oxide.', 
		manufacturer_pigment_description: 'Genuine Bronzite | Series: 3' ,
		manufacturer_name: 'Daniel Smith',
		pigments: [],
		lightfast_rating: {name: '', description: ''},
		transparency_rating: {name: '', description: ''},
		staining_rating_id: {name: '', description: ''},
		granulation_rating: {name: '', description: ''},
	}
</script>

<SwatchHeader title={paint.product_color_name} manufacturer_name={paint.manufacturer_name} />

<div class="swatch_images">
	{#each swatchCard.swatches as swatch}
		<SwatchImage id={swatch.id} />
	{/each}
</div>

<style>
	.swatch_images{
		display: flex;
	}
</style>

