<script>
	import Swatches from './Swatches.svelte'
	import SwatchHeader from './SwatchHeader.svelte'
	import SwatchQualities from './SwatchQualities.svelte';
	import SwatchDescription from './SwatchDescription.svelte';
	import SwatchPigments from './SwatchPigments.svelte';
	import SwatchSimilarProducts from './SwatchSimilarProducts.svelte';
	import SwatchStats from './SwatchStats.svelte';
	import SwatchTags from './SwatchTags.svelte';
	import SwatchNotes from './SwatchNotes.svelte';

	const swatchCard = {
		slug: 'some-autogenerated-unique-slug',
		published: true,
		tags: [{id: 1}, {id: 2}, {id: 3}],
		paint: {
			paint_type: 'Watercolor',
			product_color_name: 'Burnt Bronzite Genuine',
			product_description: 'Burnt Bronzite Genuine is a more reddish version of Bronzite. When mixed with reds, you get warm skin tones. When mixed with French Ultramarine, there is a hint of violet. With Cerulean Blue Chromium, the gray looks neutral.',
			manufacturer_product_description: 'Gorgeous Burnt Bronzite Genuine pushes the honey tone of Bronzite Genuine to a more coppery hue. Both deeper brown and more orange, its ideal for portrait work as it easily produces a wide range of flesh tones. Like Bronzite Genuine, it gets a subtle lustrous sparkle from iron oxide.', 
			manufacturer_pigment_description: 'Genuine Bronzite | Series: 3' ,
			manufacturer_name: 'Daniel Smith',
			pigments: [
				{
					code: 'PY97',
					name: 'Arylide Yellow FGL',
					image_url: 'http://placekitten.com/50/50',
					slug: 'pigments/py97',
					color: {
						name: 'Yellow',
						code: 'Y'
					},
					number: 97,
				},
				{
					code: 'PB16',
					name: 'Phthalocyanine Turquoise',
					image_url: 'http://placekitten.com/50/50',
					slug: 'pigments/pb16',
					color: {
						name: 'Blue',
						code: 'B'
					},
					number: 16,
				},
			],
			similar_products: [
				{
					product_color_name: 'Burnt Bronzite Genuine',
					manufacturer_name: 'Daniel Smith',
					image_url: 'http://placekitten.com/50/50',
					slug: 'some-autogenerated-unique-slug',
				},
				{
					product_color_name: 'Burnt Bronzite Genuine',
					manufacturer_name: 'Daniel Smith',
					image_url: 'http://placekitten.com/50/50',
					slug: 'some-autogenerated-unique-slug',
				}
			],
			qualities: {
				lightfast_rating: {name: 'I - Excellent', description: '100+ years'},
				transparency_rating: {name: 'Semi-Transparent', description: ''},
				staining_rating: {name: '1', description: 'Non Staining'},
				granulation_rating: {name: 'Yes', description: ''},
			}
		},
		swatches: [
			{
				paper: {
					manufacturer: 'Arches', 
					description: 'Cold press', 
					weight_in_lbs: 130
				},
				swatch_type: 'gradient wash granulation',
				author: {display_name: 'jane doe'},
				custom_swatch_type: null,
				description: 'some notes about this particular image',
				image_url: 'http://placekitten.com/200/300'
			},
			{
				paper: {
					manufacturer: 'Arches', 
					description: 'Hot press', 
					weight_in_lbs: 120
				},
				swatch_type: 'salted',
				author: {display_name: 'jane doe'},
				custom_swatch_type: null,
				description: 'some notes about this particular image',
				image_url: 'http://placekitten.com/300/300'
			},
		],
	}
</script>

<SwatchHeader title={swatchCard.paint.product_color_name} manufacturerName={swatchCard.paint.manufacturer_name} />
<Swatches swatches={swatchCard.swatches} />
<SwatchQualities qualities={swatchCard.paint.qualities} />
<SwatchDescription
	productDescription={swatchCard.paint.product_description}
	manufacturerProductDescription={swatchCard.paint.manufacturer_product_description}
	manufacturerPigmentDescription={swatchCard.paint.manufacturer_pigment_description}
	manufacturerName={swatchCard.paint.manufacturer_name}
/>
<SwatchPigments pigments={swatchCard.paint.pigments} />
<SwatchSimilarProducts similarProducts={swatchCard.paint.similar_products} paintType={swatchCard.paint.paint_type} />
<SwatchStats />
<SwatchTags />
