<script context="module">
	export async function load({ page, fetch, session, stuff }) {
		const url = `/swatch/${page.params.slug}.json`;
		const response = await fetch(url);

		if(response.ok) {
			return {
				props: {
					swatchData: await response.json()
				}
			}
		}

		return {
			status: response.status,
			error: new Error('Could not load.')
		}
	}
</script>

<script>
	import SwatchCards from '$lib/swatch/SwatchCards.svelte'
	import SwatchHeader from '$lib/swatch/SwatchHeader.svelte'
	import SwatchQualities from '$lib/swatch/SwatchQualities.svelte';
	import SwatchDescription from '$lib/swatch/SwatchDescription.svelte';
	import SwatchPigments from '$lib/swatch/SwatchPigments.svelte';
	import SwatchSimilarProducts from '$lib/swatch/SwatchSimilarProducts.svelte';
	import SwatchStats from '$lib/swatch/SwatchStats.svelte';
	import SwatchTags from '$lib/swatch/SwatchTags.svelte';
	import SwatchNotes from '$lib/swatch/SwatchNotes.svelte';

	export let swatchData;

	const swatch = {
		slug: 'some-autogenerated-unique-slug',
		published: true,
		tags: [
			{
				name: 'botanicals',
				slug: 'botanicals'
			},
			{
				name: 'high intensity',
				slug: 'high-intensity',
			}
		],
		paint: {
			paint_type: 'Watercolor',
			manufacturer_name: 'Daniel Smith',
			pigments: [
				{
					code: 'PY97',
					name: 'Arylide Yellow FGL',
					image_url: 'http://placekitten.com/50/50',
					slug: 'pigments/py97',
					color: {
						name: 'Yellow',
						code: 'Y'
					},
					number: 97,
				},
				{
					code: 'PB16',
					name: 'Phthalocyanine Turquoise',
					image_url: 'http://placekitten.com/50/50',
					slug: 'pigments/pb16',
					color: {
						name: 'Blue',
						code: 'B'
					},
					number: 16,
				},
			],
			similar_products: [
				{
					product_color_name: 'Burnt Bronzite Genuine',
					manufacturer_name: 'Daniel Smith',
					image_url: 'http://placekitten.com/50/50',
					slug: 'some-autogenerated-unique-slug',
				},
				{
					product_color_name: 'Burnt Bronzite Genuine',
					manufacturer_name: 'Daniel Smith',
					image_url: 'http://placekitten.com/50/50',
					slug: 'some-autogenerated-unique-slug',
				}
			],
			qualities: {
				lightfast_rating: {name: 'I - Excellent', description: '100+ years'},
				transparency_rating: {name: 'Semi-Transparent', description: ''},
				staining_rating: {name: '1', description: 'Non Staining'},
				granulation_rating: {name: 'Yes', description: ''},
			}
		},
		swatchCards: [
			{
				paper: {
					manufacturer: 'Arches', 
					description: 'Cold press', 
					weight_in_lbs: 130
				},
				swatch_type: 'gradient wash granulation',
				author: {display_name: 'jane doe'},
				custom_swatch_type: null,
				description: 'some notes about this particular image',
				image_url: 'http://placekitten.com/200/300'
			},
			{
				paper: {
					manufacturer: 'Arches', 
					description: 'Hot press', 
					weight_in_lbs: 120
				},
				swatch_type: 'salted',
				author: {display_name: 'jane doe'},
				custom_swatch_type: null,
				description: 'some notes about this particular image',
				image_url: 'http://placekitten.com/300/300'
			},
		],
		stats: [
			'<strong>19</strong> artists have this in their palette library',
			'<strong>28</strong> artists want this watercolor',
			'<strong>89%</strong> of artists who have used it are happy'
		],
		notes: [
			{
				date: '2 weeks ago',
				author: {
					display_name: 'Foo Jr.',
					initial: 'F',
				},
				body: '<p>Chrome titanate PBr24 is a very lightfast, opaque, staining, moderately light valued, moderately intense earth yellow pigment, available from about a dozen pigment manufacturers worldwide in shades ranging from green yellow through orange yellow (the shade currently used in watercolors) to dull red. The ASTM (1999) rates its lightfastness as "excellent" (I), and my own and manufacturer lightfastness tests agree. It was originally developed as a vinyl siding pigment that would weather gracefully under prolonged sunlight exposure.</p>',
				replies: [
					{
						date: '5 days ago',
						author: {
							display_name: 'Bar Baz',
							initial: 'B',
						},
						body: '<p>In watercolors PBr24 undergoes a very small drying shift, darkening by 5% and losing saturation slightly. The average CIECAM J,a,b values for chrome titanate (PBr24) are: 68, 24, 48, with chroma of 53 (estimated hue purity of 39) and a hue angle of 64. In watercolor paints described here the pigment is consistently a warm pale yellow; paints differ only in the milling and vehicle formulations.</p>'
					},
					{
						date: '5 days ago',
						author: {
							display_name: 'Fool4Paintz',
							initial: 'F',
						},
						body: '<p>In watercolors PBr24 undergoes a very small drying shift, darkening by 5% and losing saturation slightly!</p>'
					}
				]
			}
		]
	}
</script>

<SwatchHeader title={swatchData.productColorName} manufacturerName={swatch.paint.manufacturer_name} />
<SwatchCards swatchCards={swatch.swatchCards} />
<div class="row">
	<div class="column">
		<SwatchQualities qualities={swatch.paint.qualities} />
		<SwatchDescription
			communityDescription={swatchData.communityDescription}
			manufacturerDescription={swatchData.manufacturerDescription}
			manufacturerPigmentDescription={swatchData.manufacturerPigmentDescription}
			manufacturerName={swatch.paint.manufacturer_name}
		/>
	</div>
	<div class="column">
		<SwatchPigments pigments={swatch.paint.pigments} />
		<SwatchSimilarProducts similarProducts={swatch.paint.similar_products} paintType={swatch.paint.paint_type} />
		<SwatchStats stats={swatch.stats} />
		<SwatchTags tags={swatch.tags} />
	</div>
</div>
<SwatchNotes notes={swatch.notes} />

<style>
	.row {
		display: flex;
	}
</style>