name: Node.js CI

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build --if-present
      - name: Run test suite
        run: npm run test
